Repository sandboxie-plus/Sandboxie, pull requests merged in 2025-04, with the labels that each got.

#4631 Update sandman_de.ts + Fixed minor typos
  CHANGELOG.md
  SandboxiePlus/SandMan/Forms/SettingsWindow.ui
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4632 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4641 Update Text-Turkish-1055.txt
  Sandboxie/msgs/Text-Turkish-1055.txt
Labels: Type: Localization

#4646 Update Text-SimpChinese-2052.txt
  Sandboxie/msgs/Text-SimpChinese-2052.txt
Labels: Type: Localization

#4655 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4659 Update lang_zh_CN.json
  SandboxiePlus/SandMan/Troubleshooting/lang_zh_CN.json
Labels: Type: Localization

#4669 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4670 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4671 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4675 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4676 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4682 Update CHANGELOG_zh_CN.md
  CHANGELOG_zh_CN.md
Labels: Type: Localization

#4687 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4680 Update sandman_de.ts
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4695 Update CHANGELOG_zh_CN
  CHANGELOG_zh_CN.md
Labels: Type: Localization

#4691 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4696 Update Language
  Installer/Languages.iss
  SandboxiePlus/SandMan/Troubleshooting/lang_pl.json
  SandboxiePlus/SandMan/sandman_pl.ts
Labels: Type: Localization

#4702 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4704 Update sandman_pl.ts
  SandboxiePlus/SandMan/sandman_pl.ts
Labels: Type: Localization

#4716 Update sandman_pl.ts
  SandboxiePlus/SandMan/sandman_pl.ts
Labels: Type: Localization

#4722 Update sandman_pl.ts
  SandboxiePlus/SandMan/sandman_pl.ts
Labels: Type: Localization

#4719 Changelog Update in Chinese
  CHANGELOG_zh_CN.md
  README_zh_CN.md
Labels: Type: Localization

#4715 Add template for WeType
  Sandboxie/install/Templates.ini
Labels: Templates.ini

#4714 Dots. More dots. More dots. More dots.
  CHANGELOG.md
  SandboxiePlus/SandMan/Windows/SettingsWindow.cpp
Labels: User Interface

#4728 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4729 Update CHANGELOG_zh_CN.md
  CHANGELOG_zh_CN.md
Labels: Type: Localization

#4730 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4731 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4734 Update README_zh_CN.md
  README_zh_CN.md
Labels: Type: Localization

#4748 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4758 Updated Chinese translation
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4759 Updated translation
  Installer/Languages.iss
  Sandboxie/msgs/Text-SimpChinese-2052.txt
Labels: Type: Localization
