Repository sandboxie-plus/Sandboxie, pull requests merged in 2025-05, with the labels that each got.

#4771 Update lang_zh_CN.json
  SandboxiePlus/SandMan/Troubleshooting/lang_zh_CN.json
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4781 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4787 Update sandman_zh_TW.ts
  SandboxiePlus/SandMan/sandman_zh_TW.ts
Labels: Type: Localization

#4793 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4794 chore: improve hint text while IP or port is empty
  SandboxiePlus/SandMan/Windows/OptionsNetwork.cpp
  SandboxiePlus/SandMan/sandman_ar.ts
  SandboxiePlus/SandMan/sandman_de.ts
  SandboxiePlus/SandMan/sandman_en.ts
  SandboxiePlus/SandMan/sandman_es.ts
  SandboxiePlus/SandMan/sandman_fr.ts
  SandboxiePlus/SandMan/sandman_hu.ts
  SandboxiePlus/SandMan/sandman_id.ts
  SandboxiePlus/SandMan/sandman_it.ts
  SandboxiePlus/SandMan/sandman_ja.ts
  SandboxiePlus/SandMan/sandman_ko.ts
  SandboxiePlus/SandMan/sandman_nl.ts
  SandboxiePlus/SandMan/sandman_pl.ts
  SandboxiePlus/SandMan/sandman_pt_BR.ts
  SandboxiePlus/SandMan/sandman_pt_PT.ts
  SandboxiePlus/SandMan/sandman_ru.ts
  SandboxiePlus/SandMan/sandman_sv_SE.ts
  SandboxiePlus/SandMan/sandman_tr.ts
  SandboxiePlus/SandMan/sandman_uk.ts
  SandboxiePlus/SandMan/sandman_vi.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_TW.ts
Labels: User Interface, Type: Localization

#4789 Update sandman_de.ts + Text-German-1031.txt
  Sandboxie/msgs/Text-German-1031.txt
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4792 chore: update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4795 Update Chinese translation
  CHANGELOG_zh_CN.md
  README.md
  README_zh_CN.md
Labels: Type: Localization

#4796 Update sandman_ko.ts
  SandboxiePlus/SandMan/sandman_ko.ts
Labels: Type: Localization

#4798 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4784 Update README.md
  README.md
Labels: Type: Documentation

#4799 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4803 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4804 Update sandman_pl.ts
  SandboxiePlus/SandMan/sandman_pl.ts
Labels: Type: Localization

#4812 feat: adjust trace type width based on text
  SandboxiePlus/MiscHelpers/Common/CheckList.h
  SandboxiePlus/SandMan/Views/TraceView.cpp
Labels: User Interface

#4811 feat: support DNS filter even the origin domain does not exist #4359
  Sandboxie/core/dll/dns_filter.c
Labels: Type: Enhancement, Feature: DNS Filter

#4829 Update CHANGELOG.md
  CHANGELOG.md
Labels: Text Corrections

#4830 Update Turkish translations
  Sandboxie/msgs/Text-Turkish-1055.txt
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4831 Update Turkish translations
  Sandboxie/msgs/Text-Turkish-1055.txt
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4833 Typos
  Sandboxie/core/drv/conf.c
  Sandboxie/core/svc/sbieiniserver.cpp
  Sandboxie/core/svc/serviceserver2.cpp
  Sandboxie/msgs/Sbie-English-1033.txt
  SandboxiePlus/SandMan/Forms/SettingsWindow.ui
  SandboxiePlus/SandMan/Windows/PopUpWindow.cpp
Labels: Text Corrections

#4836 Update Text-German-1031.txt
  Sandboxie/msgs/Text-German-1031.txt
Labels: Type: Localization

#4839 Update sandman_de.ts
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4840 Typos
  CHANGELOG.md
  SandboxiePlus/SandMan/SandManRecovery.cpp
Labels: Text Corrections
