Repository sandboxie-plus/Sandboxie, pull requests merged in 2025-03, with the labels that each got.

#4529 Return the current copyright year (Plus installer)
  Installer/Sandboxie-Plus.iss
Labels: Sbie Installer

#4528 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4555 feat: add 'Creation Time' column to snapshot manager
  SandboxiePlus/SandMan/Windows/SnapshotsWindow.cpp
Labels: User Interface, Feature: Snapshot, Type: Enhancement

#4546 Update sandman_ko.ts
  SandboxiePlus/SandMan/sandman_ko.ts
Labels: Type: Localization

#4544 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4568 Update sandman_de.ts
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4575 Update Languages.iss
  Installer/Languages.iss
Labels: Type: Localization

#4576 Update Text-Korean-1042.txt
  Sandboxie/msgs/Text-Korean-1042.txt
Labels: Type: Localization

#4577 Update sandman_ko.ts
  SandboxiePlus/SandMan/sandman_ko.ts
Labels: Type: Localization

#4585 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4584 SandboxPlus Project Improvement
  SandboxiePlus/MiscHelpers/MiscHelpers.vcxproj
  SandboxiePlus/QSbieAPI/QSbieAPI.vcxproj
  SandboxiePlus/QtSingleApp/qtsingleapp/qtsingleapp/qtsingleapp.vcxproj
  SandboxiePlus/SandMan/SandMan.cpp
  SandboxiePlus/SandMan/SandMan.vcxproj
  SandboxiePlus/SbieShell/SbieShell/SbieShell.vcxproj
  SandboxiePlus/SbieShell/SbieShellExt/SbieShellExt.vcxproj
  SandboxiePlus/UGlobalHotkey/uglobalhotkey.vcxproj
Labels: Type: Build

#4579 context menu
  Installer/Languages.iss
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4603 Update sandman_tr.ts
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4613 Update sandman_zh_CN.ts
  README.md
  README_zh_CN.md
  Sandboxie/msgs/Text-SimpChinese-2052.txt
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4614 Typos
  Sandboxie/common/hook_util.c
  Sandboxie/core/dll/net.c
  Sandboxie/core/dll/sxs.c
  SandboxiePlus/SandMan/SandMan.cpp
  SandboxiePlus/SandMan/Views/SbieView.cpp
  SandboxiePlus/SandMan/Wizards/NewBoxWizard.cpp
Labels: Text Corrections

#4619 Update sandman_de.ts
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4617 Template for WindowGrid
  CHANGELOG.md
  Sandboxie/install/Templates.ini
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Text Corrections, Templates.ini, Type: Localization

#4625 Update sandman_de.ts
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4627 Update sandman_ko.ts
  SandboxiePlus/SandMan/sandman_ko.ts
Labels: Type: Localization
