Repository sandboxie-plus/Sandboxie, pull requests merged in 2025-07, with the labels that each got.

#4894 Add UI Font in settings windows
  SandboxiePlus/SandMan/Forms/SettingsWindow.ui
  SandboxiePlus/SandMan/Windows/SettingsWindow.cpp
  SandboxiePlus/SandMan/Windows/SettingsWindow.h
Labels: User Interface

#4898 Update Turkish translations
  Sandboxie/msgs/Text-Turkish-1055.txt
  SandboxiePlus/SandMan/sandman_tr.ts
Labels: Type: Localization

#4907 Update CHANGELOG.md
  CHANGELOG.md
Labels: Text Corrections

#4906 Update sandman_de.ts + Update Text-German-1031.txt
  Sandboxie/msgs/Text-German-1031.txt
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization

#4918 Update sandman_zh_TW.ts
  SandboxiePlus/SandMan/sandman_zh_TW.ts
Labels: Type: Localization

#4919 Improve Simplified Chinese translation
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4915 Add toggleable CSV-based INI key validation
  Installer/copy_build.cmd
  Sandboxie/install/SbieSettings.csv
  SandboxiePlus/SandMan/Forms/OptionsWindow.ui
  SandboxiePlus/SandMan/Forms/SettingsWindow.ui
  SandboxiePlus/SandMan/Helpers/IniHighlighter.cpp
  SandboxiePlus/SandMan/Helpers/IniHighlighter.h
  SandboxiePlus/SandMan/Windows/OptionsWindow.cpp
  SandboxiePlus/SandMan/Windows/OptionsWindow.h
  SandboxiePlus/SandMan/Windows/SettingsWindow.cpp
  SandboxiePlus/SandMan/Windows/SettingsWindow.h
Labels: User Interface

#4927 Add option to use the new Qt Windows 11 style on SandMan
  SandboxiePlus/SandMan/Forms/SettingsWindow.ui
  SandboxiePlus/SandMan/Windows/SettingsWindow.cpp
  SandboxiePlus/SandMan/main.cpp
Labels: User Interface

#4928 Switch key validation from CSV to INI + tooltips
  CHANGELOG.md
  Installer/copy_build.cmd
  Sandboxie/install/SbieSettings.csv
  Sandboxie/install/SbieSettings.ini
  SandboxiePlus/SandMan/Forms/OptionsWindow.ui
  SandboxiePlus/SandMan/Forms/SettingsWindow.ui
  SandboxiePlus/SandMan/Helpers/IniHighlighter.cpp
  SandboxiePlus/SandMan/Helpers/IniHighlighter.h
  SandboxiePlus/SandMan/Windows/OptionsWindow.cpp
  SandboxiePlus/SandMan/Windows/OptionsWindow.h
  SandboxiePlus/SandMan/Windows/SettingsWindow.cpp
  SandboxiePlus/SandMan/Windows/SettingsWindow.h
Labels: User Interface

#4929 Update sandman_zh_CN.ts
  SandboxiePlus/SandMan/sandman_zh_CN.ts
Labels: Type: Localization

#4930 Update sandman_de.ts
  SandboxiePlus/SandMan/sandman_de.ts
  TRANSLATING.md
Labels: Type: Localization
